# Generated by Django 4.2.2 on 2023-07-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
    ]
