# Generated by Django 4.2.2 on 2023-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=200),
        ),
    ]
