# Generated by Django 4.2.2 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, default=' ', max_length=100)),
                ('s_code', models.IntegerField(default=0)),
            ],
        ),
    ]
