# Generated by Django 4.2.2 on 2023-06-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
